version: '2'

services:
  app:
    image: webapp:0.0.1
    command: /bin/bash -c 'sleep 10000'  # go get -v && go run main.go
    build:
      context: .
    links:
      - redis
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
